---
title: "20190723_sf3b1_k700e_wt_ds"
author: "Stephanie Lozano"
date: "7/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r libraries}
library(data.table)
library(dplyr)
library(ggplot2)
library(reshape2)
library(readxl)
library(ggrepel)
library(tidyverse)
library(gplots)
library(knitr)
library("RColorBrewer")
```

```{r}
Numers <- '../output/snakemake_out_sf3b1_k700e_wt_ds/CountTableNumerators.gz'
Denoms <- '../output/snakemake_out_sf3b1_k700e_wt_ds/CountTableDenominators.gz'

NumeratorCountTable <- fread(paste0("gunzip -c ", Numers), sep=" ", header=TRUE, data.table=FALSE)
DenominatorCountTable <- fread(paste0("gunzip -c ", Denoms), sep=" ", header=TRUE, data.table=FALSE)

PSI_Table <- NumeratorCountTable[-1]/DenominatorCountTable[-1]
row.names(PSI_Table) <- gsub(":clu_.+", "", NumeratorCountTable$chrom)

#Replace NaNs from 0/0 operation
PSI_Table[is.na(PSI_Table)] <- 0

#Differential Junctions List - Darman
#DifferentialJunctionsList <- #read.table('../data/other_snakemake_data/DarmanDiffJunctions.LiftedToHg38.bed', header=F)

# Make new id, for easier use in later filtering. Note that coordinates may need to add 1 -Darman
#DifferentialJunctionsList$junc_id <- paste(DifferentialJunctionsList$V1, #DifferentialJunctionsList$V2 + 1, DifferentialJunctionsList$V3 + 1, sep=":")

#Differential Junctions List - leafcutter ID'd junctions
#Read in cluster sig text file as data frame and filter for junctions #with p value <0.1. 
SigJcns <- read.delim('../output/snakemake_out_sf3b1_k700e_e622d_ds/leafcutter.ds.cluster_sig.txt.gz') %>%
  filter(p.adjust <= 0.1, .preserve= TRUE) 


#Get chromosome/junction coords for the selected samples 
#Read in effect sizes text file, add chr:clu_ID_- in same format as "cluster" column in SigJcns, filter for chr:cluster_IDs that match those specified in SigJcns data frame.

DifferentialJunctionsList <- read.delim('../output/snakemake_out_sf3b1_k700e_e622d_ds/leafcutter.ds.effect_sizes.txt.gz', header=T) %>%
separate("intron", c("chrom", "junc_start", "junc_end", "cluster"), ":") %>%
  mutate(chr_clust= paste(chrom, cluster, sep = ":", collapse = NULL)) %>%
  filter(chr_clust %in% SigJcns$cluster, .preserve= T)


# Make new id, for easier use in later filtering. Note that coordinates may need to add 1 - leafcutter ID'd jcns
DifferentialJunctionsList$junc_id <- paste(DifferentialJunctionsList$chrom, DifferentialJunctionsList$junc_start, DifferentialJunctionsList$junc_end, sep=":")

# PCA using PSI
PCResults <- (PSI_Table) %>%
  filter(rownames(.) %in% DifferentialJunctionsList$junc_id) %>%
  t() %>%
  prcomp(center=T, scale=T)

PCResults.df <- as.data.frame(PCResults$x[,1:5]) %>% rownames_to_column()

#Read in groups table
Groups <- read.delim("../data/other_snakemake_data/sf3b1_k700e_wt_ds.groups.txt", na.strings = "NA", stringsAsFactors = T, header=F)

MutationList <- data.frame(read_excel("../data/other_snakemake_data/SeillerEtAl_MutationList.xlsx"))

# Groups table with rail_ID column

Simplified_Groups<- Groups %>%
  mutate(rail_id = sub(".project2.yangili1.snaptron.processed_to_bedfiles.SRA2.","", V1)) %>%
  mutate(label= paste(V2, rail_id, sep = " ", collapse = NULL))


#Merging Groups (rail_id and V2, or mutation) with PCResults.df into ToPlot

ToPlot <- PCResults.df %>%
  mutate(rail_id = sub(".project2.yangili1.snaptron.processed_to_bedfiles.SRA2.","", rowname)) %>% 
left_join(Simplified_Groups, by= NULL)
  
# plot PCResults.df PC1 and PC2, with labels= V2)
ggplot(ToPlot,aes(x=PC1, y=PC2, label=rail_id, color= V2)) +
  # geom_text(alpha=1, size=2.2) +
  geom_point(alpha=0.5) +
  geom_text_repel(size=2.2) +
  theme_bw()

```

It will also be nice to look at a heatmap of this feature space from which the PCA is based on.
```{r}
set.seed(0)
K700E<-ToPlot %>%
  filter(V2 =="K700E") %>%
  dplyr::pull(rowname)

WT<-ToPlot %>%
  filter(V2 =="WT") %>%
  sample_n(7) %>%
  dplyr::pull(rowname)


Heatmap <- PSI_Table %>%
  filter(rownames(.) %in% DifferentialJunctionsList$junc_id) %>%
  dplyr::select(c(K700E, WT)) %>% as.matrix() %>%
  t() %>% scale(scale=F) %>% t() %>% as.data.frame() %>% drop_na() %>% as.matrix()

#
# Heatmap <- t(scale(t(as.matrix(PSI_Table[1:10, c(Cases, Controls)]))))
# Heatmap <- scale(as.matrix(PSI_Table[1:50,c(Cases, Controls)]))

RNAExtractionDate <- as.character(unclass(factor(plyr::mapvalues(colnames(Heatmap), from=ToPlot$rowname, to=ToPlot$V2, warn_missing = FALSE) )))
RNAExtractionDate <- as.character(unclass(factor(plyr::mapvalues(colnames(Heatmap), from=ToPlot$rowname, to=ToPlot$V2, warn_missing = FALSE) )))
ColLabel = labCol <- plyr::mapvalues(colnames(Heatmap), from=ToPlot$rowname, to=ToPlot$rail_id, warn_missing = FALSE)
heatmap.2(Heatmap, col=colorRampPalette(c("blue", "white", "red"))(n = 299), dendrogram="column", trace="none", labRow="", labCol=ColLabel, ColSideColors=RNAExtractionDate, key.title="PSI-Zscore", ylab="149 splice junctions", xlab="10 samples")
```
